### ISSUE TITLE
Erro na instalação: Dotenv\Exception\ InvalidPathException

### ISSUE THREAD

**Issue by lucasarmindo** [hxphp/framework#14]
Sei que pode ser um erro muito simples, porém estou tentando instalar o framework e só recebo este erro na hora de acessar o link 

Dotenv \ Exception \ InvalidPathException
Unable to read the environment file at C:\xampp\htdocs\sistema\.env.

![image](https://user-images.githubusercontent.com/12900424/40032171-57e7425a-57c9-11e8-9959-2c3f3d3e009a.png)

**Comment by brunosantoshx** [comment]
Oi @lucasarmindo, tudo bem?

Agora existe um arquivo chamado `.env.example` na raiz que precisa ser renomeado para `.env`. É o mesmo padrão do Wordpress e Laravel (o arquivo de config precisa constar no `.gitignore` e é por isso que ele vem por padrão com um sufixo).

Forte abraço e sucesso sempre!
